routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('article');
Route::get('/dtlarticle/{slug}', 'FrontController@show')->name('dtlArticle');
Route::get('/penulis', 'FrontController@lspenulis')->name('penulis');
Route::get('/kategori', 'FrontController@lskategori')->name('kategori');
Route::get('/dtlcategory/{kategori}', 'FrontController@dtlcategory')->name('dtlCategory');
Route::get('/dtlwritter/{penulis}', 'FrontController@dtlwritter')->name('dtlWritter');

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('kakel', 'KakelController');
    Route::resource('artikel', 'ArtikelController');
    Route::resource('user', 'UserController');
    Route::resource('role', 'RoleController');
    Route::get('/profil/{profil}', 'ProfilController@index')->name('profil.index');
    Route::put('/profil/{profil}', 'ProfilController@update')->name('profil.update');
    
  });

app/Artikel.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
class Artikel extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_artikel','id_penulis','id_editor','id_kategori','judul','slug_judul','isi_artikel','status','keterangan'
    ];
    protected $table = "artikel";
    protected $primaryKey = "id_artikel";

    protected $dates = ['created_at', 'updated_at'];
    public function kakel()
    {
        return $this->belongsTo('App\Kakel', 'id_kategori', 'id_kategori');
    }
    public function penulis()
    {
        return $this->belongsTo('App\User', 'id_penulis', 'id');
    }
    public function editor()
{
    return $this->belongsTo('App\User', 'id_editor','id');
}

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
}

app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Artikel;
use App\Kakel;
use App\User;
use Notification;
use App\Notifications\WaitingList;
use App\Notifications\Congrats;
use App\Notifications\Rejected;

class ArtikelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id_role = Auth::user()->id_role;
        if ($id_role=="2") {
            $data = Artikel::whereIn('status',['Publish','Reject','Waiting List'])
            ->get();
        }else if ($id_role=='3') {
            $id = Auth::user()->id;
            $data = Artikel::where('id_penulis',$id)
            ->get();
        }
        

        $tampil['data'] = $data;

        // dd($tampil);
        return view('artikel.index', $tampil);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['artikel'] = Artikel::get();
        $data['kakel'] = Kakel::get();
        $data['editor'] = User::where('id_role',2)->get();
    //    dd($data);
            return view('artikel.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    
    $iduser = Auth::user()->id;
        $this->validate($request, [
            'judul' => 'required',
            'id_kategori' => 'required',
            'isi_artikel' => 'required',
            'status' => 'required',
            ]); 
            
   //buatslug
    $slugjudul = str_slug($request->judul);
    $request->merge(['slug_judul' => $slugjudul]);
    
    //isi name dengan nama
    $request->merge([
        'id_penulis' => $iduser,
        'id_editor' => $request->id_editor,
        'judul' => $request->judul,
        'id_kategori' => $request->id_kategori,
        'isi' => $request->isi,
        'status' => $request->status,
    ]);

    if ($request->status == "Waiting List") {
        $edtreml = User::where('id', $request->id_editor)->first();
        $edtreml->notify(new WaitingList("A new Article on your application."));

    }
     
    
    //buat data User
    $dataArtikel = Artikel::create($request->all());
 
    return redirect()->route("artikel.index")->with(
    "success",
    "Data berhasil disimpan."
     ); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function edit($id)
    {
        $data = Artikel::findOrFail($id);
        $data->penulis = User::where('id_role', 3)->get();
        $data->editor = User::where('id_role', 2)->get();
        $data->kakel = Kakel::get();
        $id_role = Auth::user()->id_role;
        if ($id_role=='3') {
            return view("artikel.edit_penulis", $data);
        }else if ($id_role=='2') {
            return view("artikel.edit_editor", $data);
        } 
       
 
        // dd($data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $iduser = Auth::user()->id;
        $this->validate($request, [
            'judul' => 'required',
            'id_kategori' => 'required',
            'isi_artikel' => 'required',
            'status' => 'required',
            ]); 
            

            $dataArtikel = Artikel::findOrFail($id);
            $dataArtikel->judul = $request->judul;
            $dataArtikel->isi_artikel = $request->isi_artikel;
            $dataArtikel->id_penulis = $request->id_penulis;
            $dataArtikel->id_editor = $request->id_editor;
            $dataArtikel->id_kategori = $request->id_kategori;
            $dataArtikel->status = $request->status;

   //buatslug
            $slugjudul = str_slug($request->judul);
            $dataArtikel->slug_judul = $slugjudul;


            if ($request->status == "Waiting List") {
                $edtreml = User::where('id', $request->id_editor)->first();
                $edtreml->notify(new WaitingList("Check New Article"));
        
            }else if ($request->status == "Publish") {
                $edtreml = User::where('id', $request->id_penulis)->first();
                $edtreml->notify(new Congrats("Good Job. Your article have been published"));
            }else if ($request->status == "Reject") {   
                $edtreml = User::where('id', $request->id_penulis)->first();
                $edtreml->notify(new Rejected("I'm Sorry, your article haven't been published. you can check your article again"));
            }
        
        return redirect()->route("artikel.index")->with(
        "success",
        "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/artikel/create.blade.php
@extends('adminlte::page')
@section('title','artikel')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen artikel</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah artikel
                </div>
                <div class="card-body">
                    <form action="{{ route('artikel.store') }}" method="post" class="form-horizontal">
                        @include('artikel.form')
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

    @section('js')
    <script src="/vendor/ckeditor/ckeditor.js"></script>
     <script>
        CKEDITOR.replace('isi_artikel', {
            width: '90%',
            height: 360
          });
        </script>
    @stop

resources/views/artikel/edit_editor.blade.php
@extends('adminlte::page')
@section('title','Artikel')
@section('content_header')
    <h1 class="m-0 text-dark">Artikel</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Edit Artikel
                </div>
                <div class="card-body">
                    <form action="{{ route('artikel.update',$id_artikel ?? '') }}" method="post" class="form-horizontal">
                        @method('PUT')
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="editor" class="col-sm-2 cotrol-label">Editor</label>
                            <div class="col-sm-10">
                                <select name="id_penulis" class="form-control">
                                    @foreach ($penulis as $item)
                                        <option value="{{ $item->id }}" {{ ( ($id_penulis ?? ''   ) == $item->id ) ? 'selected' : '' }}>
                                            {{ $item->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="editor" class="col-sm-2 cotrol-label">Editor</label>
                            <div class="col-sm-10">
                                <select name="id_editor" class="form-control">
                                    @foreach ($editor as $item)
                                        <option value="{{ $item->id }}" {{ ( ($id_editor ?? ''   ) == $item->id ) ? 'selected' : '' }}>
                                            {{ $item->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>     

                        <div class="form-group">
                            <label for="judul" class="col-sm-2 cotrol-label">Judul</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="judul" value="{{ $judul ?? ''  }}">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="kategori" class="col-sm-2 cotrol-label">kategori artikel</label>
                            <div class="col-sm-10">
                                <select name="id_kategori" class="form-control">
                                    @foreach ($kakel as $item)
                                        <option value="{{ $item->nama_kategori }}" {{ ( ($id_kategori ?? ''   ) == $item->id_kategori ) ? 'selected' : '' }}>
                                            {{ $item->nama_kategori }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="isi">isi</label>
                            <textarea name="isi_artikel"  cols="70" rows="7">{!! $isi_artikel ?? '' !!}</textarea>    
                        </div>

<div class="form-group">
    <label for="Status">Status</label>
                        <select class="form-control" name="status">
                            <option value="Draft" @if ($status ?? '' == "Draft" )
                                selected>
                                Draft
                            </option>
                            <option value="Waiting List">Waiting List</option>
                            @else
                            <option value="Waiting List" selected>Waiting List</option>
                            <option value="Draft">Draft</option>
                            
                            @endif
                        </select>
                    </div>
                         
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('artikel.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)
    @section('js')
    <script src="/vendor/ckeditor/ckeditor.js"></script>
     <script>
        CKEDITOR.replace('isi_artikel', {
            width: '90%',
            height: 360
          });
        </script>
    @stop

resources/views/artikel/edit_penulis.blade.php
@extends('adminlte::page')
@section('title','Artikel')
@section('content_header')
    <h1 class="m-0 text-dark">Artikel</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Edit Artikel
                </div>
                <div class="card-body">
                    <form action="{{ route('artikel.update',$id_artikel ?? '') }}" method="post" class="form-horizontal">
                        @method('PUT')
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="editor" class="col-sm-2 cotrol-label">Editor</label>
                            <div class="col-sm-10">
                                <select name="id_editor" class="form-control">
                                    @foreach ($editor as $item)
                                        <option value="{{ $item->id }}" {{ ( ($id_editor ?? ''   ) == $item->id ) ? 'selected' : '' }}>
                                            {{ $item->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>     

                        <div class="form-group">
                            <label for="judul" class="col-sm-2 cotrol-label">Judul</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="judul" value="{{ $judul ?? ''  }}">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="kategori" class="col-sm-2 cotrol-label">kategori artikel</label>
                            <div class="col-sm-10">
                                <select name="id_kategori" class="form-control">
                                    @foreach ($kakel as $item)
                                        <option value="{{ $item->nama_kategori }}" {{ ( ($id_kategori ?? ''   ) == $item->id_kategori ) ? 'selected' : '' }}>
                                            {{ $item->nama_kategori }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="isi">isi</label>
                            <textarea name="isi_artikel"  cols="70" rows="7">{!! $isi_artikel ?? '' !!}</textarea>    
                        </div>

<div class="form-group">
    <label for="Status">Status</label>
                        <select class="form-control" name="status">
                            <option value="Draft" @if ($status ?? '' == "Draft" )
                                selected>
                                Draft
                            </option>
                            <option value="Waiting List">Waiting List</option>
                            @else
                            <option value="Waiting List" selected>Waiting List</option>
                            <option value="Draft">Draft</option>
                            
                            @endif
                        </select>
                    </div>
<input type="hidden" class="form-control" name="id_penulis" value="{{ $id_penulis ?? ''  }}">   
                 
                         
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('artikel.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)
    @section('js')
    <script src="/vendor/ckeditor/ckeditor.js"></script>
     <script>
        CKEDITOR.replace('isi_artikel', {
            width: '90%',
            height: 360
          });
        </script>
    @stop

resources/views/artikel/form.blade.php
{{ csrf_field() }}


                        <div class="form-group">
                            <label for="judul" class="col-sm-2 cotrol-label">Judul</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="judul" value="{{ $judul ?? ''  }}">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="kategori" class="col-sm-2 cotrol-label">kategori artikel</label>
                            <div class="col-sm-10">
                                <select name="id_kategori" class="form-control">
                                    @foreach ($kakel as $item)
                                        <option value="{{ $item->id_kategori }}" {{ ( ($id_kategori ?? ''   ) == $item->id_kategori ) ? 'selected' : '' }}>
                                            {{ $item->nama_kategori }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="isi">isi</label>
                            <textarea name="isi_artikel"  cols="70" rows="7">{!! $isi_artikel ?? '' !!}</textarea>    
                        </div>


<div class="form-group">
<label for="Status">Status</label>
                    <select class="form-control" name="status">
                        <option value="Draft">
                            Draft
                        </option>
                        <option value="Waiting List">Waiting List</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="editor" class="col-sm-2 cotrol-label">Editor</label>
                    <div class="col-sm-10">
                        <select name="id_editor" class="form-control">
                            @foreach ($editor as $item)
                                <option value="{{ $item->id }}" {{ ( ($id_editor ?? ''   ) == $item->id_editor ) ? 'selected' : '' }}>
                                    {{ $item->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
<input type="hidden" class="form-control" name="emlpn" value="{{ $id_penulis ?? ''  }}">
<input type="hidden" class="form-control" name="emled" value="{{ $id_editor ?? ''  }}">
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('artikel.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>

resources/views/artikel/index.blade.php
@extends('adminlte::page')

@section('title','artikel')

@section('content_header')
<h1 class="m-0 text-dark">Artikel</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    @if (Auth::user()->id_role=="3")
                        
                    <a href="{{ route('artikel.create') }}" class="btn btn-primary btn-md">
                        <i class="fa fa-plus"> Tambah</i>
                    </a>       
                    @endif
                </div>
                    
                <div class="card-body">
                    <table class="display table table-bordered table-striped" style="width: 100%;" id="example">
                        <thead>
                            <tr>
                                <th style="width: 20px"></th>
                                
                                <th> penulis</th>
                                <th> </th>
                                <th> </th>
                                <th> status</th>
                                <th> editor</th>
                                <th style="width: 80px"> </th>
                            </tr>
                        </thead>
                        <thead>
                            <tr>
                                <th style="width: 20px">#</th>
                                
                                <th> penulis</th>
                                <th> judul</th>
                                <th> isi artikel</th>
                                <th> status</th>
                                <th> editor</th>
                                <th style="width: 80px"> Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no= 1 ; ?>
                            @foreach ($data as $item)
                                <tr>
                                    <td>
                                        {{ $no }}
                                    </td>
                                    <td>
                                        {{ $item->penulis->name }}
                                    </td>
                                    <td>
                                        {{ $item->judul }}
                                    </td>
                                    <td>
                                        {{ $item->isi_artikel }}
                                    </td>
                                    <td>
                                        {{ $item->status }}
                                    </td>
                                    <td>
                                        {{ $item->editor->name }}
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('artikel.edit', $item->id_artikel) }}" class="btn btn-success">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a onclick="hapus('{{ $item->id_artikel }}')" href="#" class="btn btn-primary">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++; ?>
                                @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
    @stop
    @section('plugins.Datatables',true)
    @section('plugins.Sweetalert2', true)
    @section('plugins.Pace',true)
    @section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable( {
            "paging":   true,
            "pagelength": 10,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "ordering": false,
            "info":     false,
            "language": {
                "zeroRecords": "No entries found. Please adjust your search parameters.",
                "info": "Showing page _PAGE_ of _PAGES_",
                "infoEmpty": "No entries found"
            },
            "stateSave": true,
            "stateDuration": 3600,
            initComplete: function () {
                this.api().columns(['4','1','5']).every( function () {
                    var column = this;
                    var select = $('<select><option value=""></option></select>')
                        .appendTo( $(column.header()).empty() )
                        .on( 'change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );
     
                            column
                                .search( val ? '^'+val+'$' : '', true, false )
                                .draw();
                        } );
     
                    column.data().unique().sort().each( function ( d, j ) {
                        select.append( '<option value="'+d+'">'+d+'</option>' )
                    } );
                } );
            }
        
        
        } );
        
    } );
    
</script>
        @if (session('success'))
            <script type="text/javascript">
                Swal.fire(
                    'Sukses!',
                    '{{ session('success') }}',
                    'success'
                )
            </script>
        @endif
            <script type="text/javascript">
                function hapus(id){
                    Swal.fire({
                        title : 'Konfirmasi',
                        text : "Yakin ingin menghapus data ini ?",
                        icon : 'warning',
                        showCancelButton : true,
                        confirmButtonColor : '#3085d6',
                        cancelButtonColor: '#dd3333',
                        confirmButtonText: 'Hapus',
                        cancelButtonText: 'Batal',
                    }).then((result) =>  {
                        if (result.value){
                            $.ajax({
                                url: "/artikel/"+id,
                                type: 'DELETE',
                                data:{
                                    '_token' : $('meta[name=csrf-token]').attr("content"),
                                },
                                success : function(result){
                                    Swal.fire(
                                        'Sukses!',
                                        'Berhasil dihapus',
                                        'success'
                                    );
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            </script>
       
            @stop