routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('article');
Route::get('/dtlarticle/{slug}', 'FrontController@show')->name('dtlArticle');
Route::get('/penulis', 'FrontController@lspenulis')->name('penulis');
Route::get('/kategori', 'FrontController@lskategori')->name('kategori');
Route::get('/dtlcategory/{kategori}', 'FrontController@dtlcategory')->name('dtlCategory');
Route::get('/dtlwritter/{penulis}', 'FrontController@dtlwritter')->name('dtlWritter');

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('kakel', 'KakelController');
    Route::resource('artikel', 'ArtikelController');
    Route::resource('user', 'UserController');
    Route::resource('role', 'RoleController');
    Route::get('/profil/{profil}', 'ProfilController@index')->name('profil.index');
    Route::put('/profil/{profil}', 'ProfilController@update')->name('profil.update');
    
  });

app/Role.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Role extends Authenticatable
{
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_role','role_name'
    ];
    protected $primaryKey = 'id_role';
    protected $table = "roles";
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
 
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Role::get();
        
     
        $tampil['data'] = $data;

        // dd($tampil);
        return view('role.index', $tampil);
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['role'] = Role::get();
        
        return view('role.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'role_name' => 'required'
            ]); 
            
    
    //buat data Role
    $dataRole = Role::create($request->all());
 
    return redirect()->route("role.index")->with(
    "success",
    "Data berhasil disimpan."
     ); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Role::findOrFail($id);
        
        return view("role.edit", $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         //validasi inputan
         $this->validate($request, [
            'role_name' => 'required'
            ]);
           
            $dataRole = Role::findOrFail($id);
            $dataRole->role_name = $request->role_name;
    
            $dataRole->save();
        
        return redirect()->route("role.index")->with(
        "success",
        "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dataRole = Role::findOrFail($id);
        $dataRole->delete();

    }
}

resources/views/role/create.blade.php
@extends('adminlte::page')
@section('title','role')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen role</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah role
                </div>
                <div class="card-body">
                    <form action="{{ route('role.store') }}" method="post" class="form-horizontal">
                        @include('role.form')
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

resources/views/role/edit.blade.php
@extends('adminlte::page')
@section('title','role')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen role</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah role
                </div>
                <div class="card-body">
                    <form action="{{ route('role.update',$id_role ?? '') }}" method="post" class="form-horizontal">
                        @method('PUT')
                        {{ csrf_field() }}

<div class="form-group">
    <label for="nama" class="col-sm-2 cotrol-label">Nama</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="role_name" value="{{ $role_name ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('role.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

resources/views/role/form.blade.php
{{ csrf_field() }}

<div class="form-group">
    <label for="nama" class="col-sm-2 cotrol-label">Nama Role</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="role_name" value="{{ $role_name ?? ''  }}">
    </div>
</div>

<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('role.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>

resources/views/role/index.blade.php
@extends('adminlte::page')

@section('title','role')

@section('content_header')
<h1 class="m-0 text-dark">Manajemen role</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <a href="{{ route('role.create') }}" class="btn btn-primary btn-md">
                        <i class="fa fa-plus"> Tambah</i>
                    </a>       
                </div>
                <div class="card-body">
                    <table class="display table table-bordered table-striped" id="example">
                        <thead>
                            <tr>
                                <th style="width: 20px">#</th>
                                <th> nama role</th>
                                <th style="width: 80px"> Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no= 1 ; ?>
                            @forelse ($data as $item)
                                <tr>
                                    <td>
                                        {{ $no }}
                                    </td>
                                    <td>
                                        {{ $item->role_name }}
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('role.edit', $item->id_role) }}" class="btn btn-success">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a onclick="hapus('{{ $item->id_role }}')" href="#" class="btn btn-primary">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++; ?>
                            @empty
                                <tr>
                                    <td colspan="6">
                                        Tidak Ada Data
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
              
            </div>
        </div>
    </div>
    @stop
    @section('plugins.Datatables',true)
    @section('plugins.Sweetalert2', true)
    @section('plugins.Pace',true)
    
    @section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable( {
            "paging":   true,
            "pagelength": 10,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "ordering": false,
            "info":     false,
            "language": {
                "zeroRecords": "No entries found. Please adjust your search parameters.",
                "info": "Showing page _PAGE_ of _PAGES_",
                "infoEmpty": "No entries found"
            },
        } );
        
    } );
    
</script>
        @if (session('success'))
            <script type="text/javascript">
                Swal.fire(
                    'Sukses!',
                    '{{ session('success') }}',
                    'success'
                )
            </script>
        @endif
            <script type="text/javascript">
                function hapus(id){
                    Swal.fire({
                        title : 'Konfirmasi',
                        text : "Yakin ingin menghapus data ini ?",
                        icon : 'warning',
                        showCancelButton : true,
                        confirmButtonColor : '#3085d6',
                        cancelButtonColor: '#dd3333',
                        confirmButtonText: 'Hapus',
                        cancelButtonText: 'Batal',
                    }).then((result) =>  {
                        if (result.value){
                            $.ajax({
                                url: "/role/"+id,
                                type: 'DELETE',
                                data:{
                                    '_token' : $('meta[name=csrf-token]').attr("content"),
                                },
                                success : function(result){
                                    Swal.fire(
                                        'Sukses!',
                                        'Berhasil dihapus',
                                        'success'
                                    );
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            </script>
            @stop