routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('article');
Route::get('/dtlarticle/{slug}', 'FrontController@show')->name('dtlArticle');
Route::get('/penulis', 'FrontController@lspenulis')->name('penulis');
Route::get('/kategori', 'FrontController@lskategori')->name('kategori');
Route::get('/dtlcategory/{kategori}', 'FrontController@dtlcategory')->name('dtlCategory');
Route::get('/dtlwritter/{penulis}', 'FrontController@dtlwritter')->name('dtlWritter');

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('kakel', 'KakelController');
    Route::resource('artikel', 'ArtikelController');
    Route::resource('user', 'UserController');
    Route::resource('role', 'RoleController');
    Route::get('/profil/{profil}', 'ProfilController@index')->name('profil.index');
    Route::put('/profil/{profil}', 'ProfilController@update')->name('profil.update');
    
  });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Auth;
use App\Role;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id_role','foto','name', 'email', 'password',
    ];
    protected $table = "users";
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
    public function adminlte_image()
    {
        $foto = Auth::user()->foto;
        return '/assets/picture/'.$foto;
    }

    public function adminlte_desc()
    {
        $id_role = Auth::user()->id_role;
        $role_name = Role::findOrfail($id_role);
        return 'Tipe User : '.$role_name['role_name'];
    }

    public function adminlte_profile_url()
    {
        $id= Auth::user()->id;
        return 'profil/'.$id;
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
{
    return $this->belongsTo('App\Role', 'id_role');
}



}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::get();
        
     
        $tampil['data'] = $data;

        // dd($tampil);
        return view('user.index', $tampil);
    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = User::get();
        $data['hak_akses'] = Role::get();
    //    dd($data);
            return view('user.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
           $this->validate($request, [
            'name' => 'required',
            'hak_akses' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required',
            ]); 
            
   //enkripsi password
    $enkripsi = Hash::make($request->password);
    $request->merge(['password' => $enkripsi]);
    
    //isi name dengan nama
    $request->merge([
        'foto' => 'user.jpg',
        'name' => $request->name,
    'id_role' => $request->hak_akses
    ]);
     
    
    //buat data User
    $dataUser = User::create($request->all());
 
    return redirect()->route("user.index")->with(
    "success",
    "Data berhasil disimpan."
     ); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::findOrFail($id);
        $data->role = Role::get();
        
        return view("user.edit", $data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validasi inputan
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
            'hak_akses' => 'required',
            ]);
           
            $dataUser = User::findOrFail($id);
            $dataUser->name = $request->name;
            $dataUser->email = $request->email;
            $dataUser->id_role = $request->hak_akses;
    
            //jika password tidak kosong
            if ($request->password!="") {
            $enkripsi = Hash::make($request->password);
            $dataUser->password = $enkripsi;
            }
            $dataUser->save();
        
        return redirect()->route("user.index")->with(
        "success",
        "Data berhasil diubah."
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dataUser = User::findOrFail($id);
        $dataUser->delete();


    }
}

resources/views/user/create.blade.php
@extends('adminlte::page')
@section('title','user')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen user</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah user
                </div>
                <div class="card-body">
                    <form action="{{ route('user.store') }}" method="post" class="form-horizontal">
                        @include('user.form')
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

resources/views/user/edit.blade.php
@extends('adminlte::page')
@section('title','user')
@section('content_header')
    <h1 class="m-0 text-dark">Manajemen user</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah user
                </div>
                <div class="card-body">
                    <form action="{{ route('user.update',$id ?? '') }}" method="post" class="form-horizontal">
                        @method('PUT')
                        {{ csrf_field() }}

<div class="form-group">
    <label for="nama" class="col-sm-2 cotrol-label">Nama</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="name" value="{{ $name ?? ''  }}">
    </div>
</div>

<div class="form-group">
    <label for="email" class="col-sm-2 cotrol-label">Email</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="email" value="{{ $email ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="password" class="col-sm-2 cotrol-label">Password</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="jika tidak ingin diubah,tak perlu di isi" name="password" value="{{ $password ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="hak_akses" class="col-sm-2 cotrol-label">Hak Akses</label>
    <div class="col-sm-10">
        <select name="hak_akses" class="form-control">
            @foreach ($role as $item)
                <option value="{{ $item->id_role }}" {{ ( ($hak_akses ?? ''   ) == $item->role_name ) ? 'selected' : '' }}>
                   {{ $item->role_name }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('user.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

resources/views/user/form.blade.php
{{ csrf_field() }}

<div class="form-group">
    <label for="nama" class="col-sm-2 cotrol-label">Nama</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="name" value="{{ $name ?? ''  }}">
    </div>
</div>

<div class="form-group">
    <label for="email" class="col-sm-2 cotrol-label">Email</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="email" value="{{ $email ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="password" class="col-sm-2 cotrol-label">Password</label>
    <div class="col-sm-10">
        <input type="password" class="form-control" name="password" value="{{ $password ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <label for="hak_akses" class="col-sm-2 cotrol-label">Hak Akses</label>
    <div class="col-sm-10">
        <select name="hak_akses" class="form-control">
            @foreach ($hak_akses as $item)
                <option value="{{ $item->id_role }}" {{ ( ($hak_akses ?? ''   ) == $item->role_name ) ? 'selected' : '' }}>
                    {{ $item->role_name }}
                </option>
            @endforeach
        </select>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('user.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>

resources/views/user/index.blade.php
@extends('adminlte::page')

@section('title','user')

@section('content_header')
<h1 class="m-0 text-dark">Manajemen user</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <a href="{{ route('user.create') }}" class="btn btn-primary btn-md">
                        <i class="fa fa-plus"> Tambah</i>
                    </a>       
                </div>
                <div class="card-body">
                    <table class="display table table-bordered table-striped" id="example">
                        <thead>
                            <tr>
                                <th style="width: 20px">#</th>
                                <th> nama user</th>
                                <th> email</th>
                                <th> hak akses</th>
                                <th style="width: 80px"> Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no= 1 ; ?>
                            @foreach ($data as $item)
                                <tr>
                                    <td>
                                        {{ $no }}
                                    </td>
                                    <td>
                                        {{ $item->name }}
                                    </td>
                                    <td>
                                        {{ $item->email }}
                                    </td>
                                    <td id="role_name">
                                      {{ $item->roles->role_name }}
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('user.edit', $item->id) }}" class="btn btn-success">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a onclick="hapus('{{ $item->id }}')" href="#" class="btn btn-primary">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++; ?>
                            @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
    @stop
    @section('plugins.Datatables',true)
    @section('plugins.Sweetalert2', true)
    @section('plugins.Pace',true)
    
    @section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable( {
            "paging":   true,
            "pagelength": 10,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "ordering": false,
            "info":     false,
            "language": {
                "zeroRecords": "No entries found. Please adjust your search parameters.",
                "info": "Showing page _PAGE_ of _PAGES_",
                "infoEmpty": "No entries found"
            },
        } );
        
    } );
    
</script>
        @if (session('success'))
            <script type="text/javascript">
                Swal.fire(
                    'Sukses!',
                    '{{ session('success') }}',
                    'success'
                )
            </script>
        @endif
            <script type="text/javascript">
                function hapus(id){
                    Swal.fire({
                        title : 'Konfirmasi',
                        text : "Yakin ingin menghapus data ini ?",
                        icon : 'warning',
                        showCancelButton : true,
                        confirmButtonColor : '#3085d6',
                        cancelButtonColor: '#dd3333',
                        confirmButtonText: 'Hapus',
                        cancelButtonText: 'Batal',
                    }).then((result) =>  {
                        if (result.value){
                            $.ajax({
                                url: "/user/"+id,
                                type: 'DELETE',
                                data:{
                                    '_token' : $('meta[name=csrf-token]').attr("content"),
                                },
                                success : function(result){
                                    Swal.fire(
                                        'Sukses!',
                                        'Berhasil dihapus',
                                        'success'
                                    );
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            </script>
            @stop