routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@index')->name('article');
Route::get('/dtlarticle/{slug}', 'FrontController@show')->name('dtlArticle');
Route::get('/penulis', 'FrontController@lspenulis')->name('penulis');
Route::get('/kategori', 'FrontController@lskategori')->name('kategori');
Route::get('/dtlcategory/{kategori}', 'FrontController@dtlcategory')->name('dtlCategory');
Route::get('/dtlwritter/{penulis}', 'FrontController@dtlwritter')->name('dtlWritter');

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function () {
    Route::resource('kakel', 'KakelController');
    Route::resource('artikel', 'ArtikelController');
    Route::resource('user', 'UserController');
    Route::resource('role', 'RoleController');
    Route::get('/profil/{profil}', 'ProfilController@index')->name('profil.index');
    Route::put('/profil/{profil}', 'ProfilController@update')->name('profil.update');
    
  });

app/Kakel.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Kakel extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = "kakel";
    protected $fillable = [
        'id_kategori','nama_kategori'
        ];
        protected $primaryKey = 'id_kategori';
       
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */

}

app/Http/Controllers/KakelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kakel;
class KakelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Kakel::get();
        
     
        $tampil['data'] = $data;

        // dd($tampil);
        return view('kakel.index', $tampil);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kakel'] = Kakel::get();
        
        return view('kakel.create',$data);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_kategori' => 'required'
            ]); 
            
    
    //buat data Kakel
    $dataKakel = Kakel::create($request->all());
 
    return redirect()->route("kakel.index")->with(
    "success",
    "Data berhasil disimpan."
     );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Kakel::findOrFail($id);
        
        return view("kakel.edit", $data);
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
            //validasi inputan
            $this->validate($request, [
                'nama_kategori' => 'required'
                ]);
               
                $dataKakel = Kakel::findOrFail($id);
                $dataKakel->nama_kategori = $request->nama_kategori;
        
                $dataKakel->save();
            
            return redirect()->route("kakel.index")->with(
            "success",
            "Data berhasil diubah."
            );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dataKakel = Kakel::findOrFail($id);
        $dataKakel->delete();
    }
}

resources/views/kakel/create.blade.php
@extends('adminlte::page')
@section('title','Kategori')
@section('content_header')
    <h1 class="m-0 text-dark">Kategori Artikel</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Tambah Kategori
                </div>
                <div class="card-body">
                    <form action="{{ route('kakel.store') }}" method="post" class="form-horizontal">
                        @include('kakel.form')
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

resources/views/kakel/edit.blade.php
@extends('adminlte::page')
@section('title','Kategori')
@section('content_header')
    <h1 class="m-0 text-dark">Kategori Artikel</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" data-dismiss="alert" class="close" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i>Perhatian!</h4>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            
            <div class="card">
                <div class="card-header">
                    Edit Kategori
                </div>
                <div class="card-body">
                    <form action="{{ route('kakel.update',$id_kategori ?? '') }}" method="post" class="form-horizontal">
                        @method('PUT')
                        {{ csrf_field() }}

<div class="form-group">
    <label for="nama" class="col-sm-2 cotrol-label">Kategori Artikel</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="nama_kategori" value="{{ $nama_kategori ?? ''  }}">
    </div>
</div>
<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('kakel.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>
                    </form>
                </div>
            </div>

        </div> 
    </div>
    @stop
    @section('plugins.Pace',true)

resources/views/kakel/form.blade.php
{{ csrf_field() }}

<div class="form-group">
    <label for="kategori artikel" class="col-sm-2 cotrol-label">Kategori Artikel</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="nama_kategori" value="{{ $nama_kategori ?? ''  }}">
    </div>
</div>

<div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
        <input type="submit" class="btn btn-md btn-success" name="simpan" value="Simpan">
        <a href="{{ route('kakel.index') }}" role="button" class="btn btn-primary">Batal</a>
    </div>
</div>

resources/views/kakel/index.blade.php
@extends('adminlte::page')

@section('title','kakel')

@section('content_header')
<h1 class="m-0 text-dark">Manajemen Kategori Artikel</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <a href="{{ route('kakel.create') }}" class="btn btn-primary btn-md">
                        <i class="fa fa-plus"> Tambah</i>
                    </a>       
                </div>
                <div class="card-body">
                    <table class="display table table-bordered table-striped" id="example">
                        <thead>
                            <tr>
                                <th style="width: 20px">#</th>
                                <th> nama kakel</th>
                                <th style="width: 80px"> Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no= 1 ; ?>
                            @foreach ($data as $item)
                                <tr>
                                    <td>
                                        {{ $no }}
                                    </td>
                                    <td>
                                        {{ $item->nama_kategori }}
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('kakel.edit', $item->id_kategori) }}" class="btn btn-success">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a onclick="hapus('{{ $item->id_kategori }}')" href="#" class="btn btn-primary">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <?php $no++; ?>
                            @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
    @stop
    @section('plugins.Datatables',true)
    @section('plugins.Sweetalert2', true)
    @section('plugins.Pace',true)
    
    @section('js')
<script>
    $(document).ready(function() {
        $('#example').DataTable( {
            "paging":   true,
            "pagelength": 10,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "ordering": false,
            "info":     false,
            "language": {
                "zeroRecords": "No entries found. Please adjust your search parameters.",
                "info": "Showing page _PAGE_ of _PAGES_",
                "infoEmpty": "No entries found"
            },
        } );
        
    } );
    
</script>
        @if (session('success'))
            <script type="text/javascript">
                Swal.fire(
                    'Sukses!',
                    '{{ session('success') }}',
                    'success'
                )
            </script>
        @endif
            <script type="text/javascript">
                function hapus(id){
                    Swal.fire({
                        title : 'Konfirmasi',
                        text : "Yakin ingin menghapus data ini ?",
                        icon : 'warning',
                        showCancelButton : true,
                        confirmButtonColor : '#3085d6',
                        cancelButtonColor: '#dd3333',
                        confirmButtonText: 'Hapus',
                        cancelButtonText: 'Batal',
                    }).then((result) =>  {
                        if (result.value){
                            $.ajax({
                                url: "/kakel/"+id,
                                type: 'DELETE',
                                data:{
                                    '_token' : $('meta[name=csrf-token]').attr("content"),
                                },
                                success : function(result){
                                    Swal.fire(
                                        'Sukses!',
                                        'Berhasil dihapus',
                                        'success'
                                    );
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            </script>
            @stop